# Generated by Django 5.0.1 on 2024-05-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RescueReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.URLField()),
                ("situation", models.TextField()),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="pictures/"),
                ),
                ("video", models.FileField(blank=True, null=True, upload_to="videos/")),
                ("animal_type", models.CharField(max_length=50)),
                (
                    "behavior",
                    models.CharField(
                        choices=[
                            ("friendly", "Friendly"),
                            ("aggressive", "Aggressive"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "keep_at_place",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                (
                    "bring_to_shelter",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                (
                    "adopt_after_treatment",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
            ],
        ),
    ]
