# Generated by Django 5.0.1 on 2024-05-17 22:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qheartsmain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescuereport",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
